name: dart_jts
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://www.hydrologis.com
author: Andrea Antonello <andrea.antonello@gmail.com>
repository: https://github.com/moovida/dart_jts
issue_tracker: https://github.com/moovida/dart_jts/issues

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  intl: ^0.16.0
  hex: ^0.1.2

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.9.4
